version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lahacks2020
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    environment:
      - SECRET_KEY=)y2eio3x3@l0efay3=6ky&n!dx)$ebp&otd$f2k(enf9q))rrt
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
