version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lahacks2020
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate; python manage.py runserver 0.0.0.0:80'
    environment:
      - SECRET_KEY=)y2eio3x3@l0efay3=6ky&n!dx)$ebp&otd$f2k(enf9q))rrt
      - GOOGLE_APPLICATION_CREDENTIALS=./lahacks2020-603cfe6eaace.json
      - AZURE_KEY=848daf0ac94b414f845cf03a355c037f
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
