# Generated by Django 3.0.4 on 2020-03-28 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('verification_url', models.CharField(max_length=512)),
                ('point_value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamify.Team'),
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamify.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamify.MasterTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamify.User')),
            ],
        ),
        migrations.CreateModel(
            name='MasterChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('prize', models.CharField(max_length=100)),
                ('daily_point_limit', models.IntegerField()),
                ('team_size_limit', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('mastertasks', models.ManyToManyField(to='gamify.MasterTask')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamify.MasterChallenge')),
                ('scores', models.ManyToManyField(to='gamify.TeamScore')),
                ('tasks', models.ManyToManyField(to='gamify.TaskInstance')),
                ('teams', models.ManyToManyField(to='gamify.Team')),
            ],
        ),
    ]
