# Generated by Django 3.0.4 on 2020-03-28 22:52

from django.db import migrations


def load_challenges_and_tasks(apps, schema_editor):
    MasterTask = apps.get_model('gamify', 'MasterTask')
    task_one = MasterTask(
        name="An Apple A Day",
        description="Take a picture of yourself eating an apple!",
        verification_url="/verify/apple",
        point_value=1,
    )
    task_two = MasterTask(
        name="Quality Time Over Facetime",
        description="Take a picture of yourself video calling a friend!",
        verification_url="/verify/video",
        point_value=1,
    )
    task_three = MasterTask(
        name="Knowledge Is Power",
        description="Take a picture of yourself reading a book!",
        verification_url="/verify/book",
        point_value=1,
    )
    task_four = MasterTask(
        name="Beat The Sun",
        description="Take a picture of yourself waking up at 5:30 AM!",
        verification_url="/verify/sunrise",
        point_value=1,
    )
    task_one.save()
    task_two.save()
    task_three.save()
    task_four.save()

    MasterChallenge = apps.get_model('gamify', 'MasterChallenge')
    challenge_one = MasterChallenge(
        name="Wellness",
        description="Quarantine isn't an excuse to forget about your personal health! Enroll in this challenge today and start building healthier habits.",
        prize="A one year subscription to Headspace for each team member",
        daily_point_limit=6,
        team_size_limit=8,
        number_of_days=7,
    )
    challenge_one.save()
    challenge_one.mastertasks.add(task_one, task_two, task_three, task_four)
    challenge_one.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0002_auto_20200328_2251'),
    ]

    operations = [
        migrations.RunPython(load_challenges_and_tasks),
    ]
