# Generated by Django 3.0.4 on 2020-03-29 07:09

from django.db import migrations, models
import gamify.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0003_taskinstance_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=gamify.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='challengeinstance',
            name='scores',
            field=models.ManyToManyField(blank=True, to='gamify.TeamScore'),
        ),
        migrations.AlterField(
            model_name='challengeinstance',
            name='teams',
            field=models.ManyToManyField(blank=True, to='gamify.Team'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='date',
            field=models.DateField(),
        ),
    ]
