# Generated by Django 3.0.4 on 2020-03-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0003_auto_20200328_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
