# Generated by Django 3.0.4 on 2020-03-29 02:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0004_auto_20200329_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeinstance',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='masterchallenge',
            name='mastertasks',
        ),
        migrations.AddField(
            model_name='challengeinstance',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 2, 50, 14, 525897)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mastertask',
            name='challenge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='master_tasks', to='gamify.MasterChallenge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challengeinstance',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_instances', to='gamify.MasterChallenge'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='gamify.MasterTask'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gamify.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='gamify.Team'),
        ),
    ]
