# Generated by Django 3.0.4 on 2020-03-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0005_auto_20200329_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinstance',
            old_name='task',
            new_name='masterTask',
        ),
    ]
